name: Build DMS Core

on:
  push:
    branches: [ master, main, ver/26.1.2 ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global user.email "dmscore@build.local"
          git config --global user.name "DMS Core Build"

      - name: Setup Java 25
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 25

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Apply Patches
        run: ./gradlew applyAllPatches --stacktrace
      - name: Inject DMS Core config
        run: |
          FILE="purpur-server/src/minecraft/java/net/minecraft/server/dedicated/DedicatedServer.java"
          sed -i '284a\        // DMS Core start - story-core.yml\n        try {\n            org.purpurmc.purpur.dmscore.DMSCoreConfig.init(new java.io.File("story-core.yml"));\n        } catch (Exception e) {\n            DedicatedServer.LOGGER.error("Unable to load DMS Core configuration", e);\n            return false;\n        }\n        // DMS Core end - story-core.yml' "$FILE"

      - name: Build
        run: ./gradlew build --stacktrace

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: DMS-Core-${{ github.run_number }}
          path: purpur-server/build/libs/purpur-*.jar
          if-no-files-found: error
